version: 2
references:
  workspace_root: &workspace_root
    ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  npm_cache_keys: &npm_cache_keys
    keys:
        - v1-npm-cache-{{ checksum "package.json" }}
  cache_npm_cache: &cache_npm_cache
    save_cache:
        key: v1-npm-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules/
  restore_npm_cache: &restore_npm_cache
    restore_cache:
        <<: *npm_cache_keys
jobs:
  build:
    working_directory: ~/project/build
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install project dependencies
          command: npm install
      - *cache_npm_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build
  lint:
    working_directory: ~/project/build
    docker:
      - image: circleci/node:lts
    steps:
      - *attach_workspace
      - run:
          name: Lint JavaScript
          command: npm run lint:js
workflows:
  version: 2
  build-validate:
    jobs:
      - build
      - lint:
          requires:
            - build
