version: 2.1
parameters:
  node_version:
    type: integer
    default: 12
  cache_version:
    type: integer
    default: 1
orbs:
  node-module: maxcbc/node-module@0.0.3
executors:
  nodejs:
    docker:
      - image: circleci/node:<< pipeline.parameters.node_version >>
    resource_class: small
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - node-module/npm_install:
          cache_version: << pipeline.parameters.cache_version >>
      - run:
          name: eslint
          command: |
            mkdir -p test-results/eslint
            eslint -f junit "**/*.js" > test-results/eslint/lint.xml
      - store_test_results:
          path: test-results

  publish:
    executor: nodejs
    steps:
      - checkout
      - node-module/login_to_github_package_registry
      - node-module/restore_cached_node_modules:
          cache_version: << pipeline.parameters.cache_version >>
      - node-module/publish_to_github_package_registry

workflows:
  version: 2.1
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
